"""v02 worker identity on runs

Revision ID: 0d5b0a2d906e
Revises: e2fac042908e
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0d5b0a2d906e"
down_revision: str | Sequence[str] | None = "e2fac042908e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runs", sa.Column("worker_id", sa.String(length=100), nullable=True))
    op.execute(sa.text("UPDATE runs SET worker_id = lease_owner WHERE lease_owner IS NOT NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "worker_id")
    # ### end Alembic commands ###
