"""v02 execution spec foundation

Revision ID: 3189d7ad9821
Revises: b5c269a42b8f
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3189d7ad9821"
down_revision: str | Sequence[str] | None = "b5c269a42b8f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution_specs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("agent_id", sa.String(length=36), nullable=False),
        sa.Column("agent_revision", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("runtime_version", sa.String(length=20), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("agents", sa.Column("revision", sa.Integer(), server_default="1", nullable=False))
    op.alter_column("agents", "revision", server_default=None)
    op.add_column("runs", sa.Column("execution_spec_id", sa.String(length=36), nullable=True))
    op.add_column("runs", sa.Column("runtime_version", sa.String(length=20), nullable=True))
    op.create_foreign_key(
        "fk_runs_execution_spec_id_execution_specs",
        "runs",
        "execution_specs",
        ["execution_spec_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_runs_execution_spec_id_execution_specs", "runs", type_="foreignkey")
    op.drop_column("runs", "runtime_version")
    op.drop_column("runs", "execution_spec_id")
    op.drop_column("agents", "revision")
    op.drop_table("execution_specs")
    # ### end Alembic commands ###
