"""v02 catalog and conversation lifecycle

Revision ID: 64fce2d9b27d
Revises: 72592a423095
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "64fce2d9b27d"
down_revision: str | Sequence[str] | None = "72592a423095"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "model_configs", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "model_configs",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "model_configs",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "sessions", sa.Column("title", sa.String(length=200), server_default="", nullable=False)
    )
    op.alter_column("sessions", "title", server_default=None)
    op.add_column("sessions", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "sessions",
        sa.Column(
            "last_active_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("tools", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "tools",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "tools",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tools", "updated_at")
    op.drop_column("tools", "created_at")
    op.drop_column("tools", "archived_at")
    op.drop_column("sessions", "last_active_at")
    op.drop_column("sessions", "archived_at")
    op.drop_column("sessions", "title")
    op.drop_column("model_configs", "updated_at")
    op.drop_column("model_configs", "created_at")
    op.drop_column("model_configs", "archived_at")
    op.drop_column("agents", "archived_at")
    # ### end Alembic commands ###
