"""v02 artifact metadata

Revision ID: 7c92f0a5b8fe
Revises: a69ba1f5b592
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7c92f0a5b8fe"
down_revision: str | Sequence[str] | None = "a69ba1f5b592"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("message_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("mime_type", sa.String(length=150), nullable=False),
        sa.Column("storage_provider", sa.String(length=20), nullable=False),
        sa.Column("storage_key", sa.String(length=100), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_artifacts_conversation_created",
        "artifacts",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_artifacts_run_id"), "artifacts", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_artifacts_run_id"), table_name="artifacts")
    op.drop_index("ix_artifacts_conversation_created", table_name="artifacts")
    op.drop_table("artifacts")
    # ### end Alembic commands ###
