"""v02 durable run trace

Revision ID: a69ba1f5b592
Revises: 0d5b0a2d906e
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a69ba1f5b592"
down_revision: str | Sequence[str] | None = "0d5b0a2d906e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run_trace_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_run_trace_events_run_id_id", "run_trace_events", ["run_id", "id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_run_trace_events_run_id_id", table_name="run_trace_events")
    op.drop_table("run_trace_events")
    # ### end Alembic commands ###
