"""v02 menu hierarchy

Revision ID: b5c269a42b8f
Revises: 64fce2d9b27d
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b5c269a42b8f"
down_revision: str | Sequence[str] | None = "64fce2d9b27d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("menus", sa.Column("parent_id", sa.String(length=36), nullable=True))
    op.add_column("menus", sa.Column("component", sa.String(length=250), nullable=True))
    op.create_foreign_key("menus_parent_id_fkey", "menus", "menus", ["parent_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("menus_parent_id_fkey", "menus", type_="foreignkey")
    op.drop_column("menus", "component")
    op.drop_column("menus", "parent_id")
    # ### end Alembic commands ###
