"""add_run_lease_owner

Revision ID: cbf444d5ad1e
Revises: 23a58f24a52a
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cbf444d5ad1e"
down_revision: str | Sequence[str] | None = "23a58f24a52a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runs", sa.Column("lease_owner", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "lease_owner")
    # ### end Alembic commands ###
