"""v02 retry lineage

Revision ID: dc84f248f881
Revises: ec3e80993c27
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dc84f248f881"
down_revision: str | Sequence[str] | None = "ec3e80993c27"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runs", sa.Column("parent_run_id", sa.String(length=36), nullable=True))
    op.add_column("runs", sa.Column("attempt", sa.Integer(), server_default="1", nullable=False))
    op.add_column(
        "runs", sa.Column("origin", sa.String(length=20), server_default="CLIENT", nullable=False)
    )
    op.alter_column("runs", "attempt", server_default=None)
    op.alter_column("runs", "origin", server_default=None)
    op.add_column("runs", sa.Column("started_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("runs", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f("runs_message_id_key"), "runs", type_="unique")
    op.create_foreign_key("fk_runs_parent_run_id_runs", "runs", "runs", ["parent_run_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_runs_parent_run_id_runs", "runs", type_="foreignkey")
    op.create_unique_constraint(
        op.f("runs_message_id_key"), "runs", ["message_id"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("runs", "completed_at")
    op.drop_column("runs", "started_at")
    op.drop_column("runs", "origin")
    op.drop_column("runs", "attempt")
    op.drop_column("runs", "parent_run_id")
    # ### end Alembic commands ###
