"""v02 agent revision history

Revision ID: e2fac042908e
Revises: 5a9d256474b6
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e2fac042908e"
down_revision: str | Sequence[str] | None = "5a9d256474b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("agent_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "revision"),
    )
    op.create_index(
        op.f("ix_agent_revisions_agent_id"), "agent_revisions", ["agent_id"], unique=False
    )
    op.execute(
        sa.text("""
        INSERT INTO agent_revisions (id, agent_id, revision, snapshot)
        SELECT md5(random()::text || a.id || clock_timestamp()::text),
               a.id, a.revision,
               json_build_object(
                   'name', a.name,
                   'description', a.description,
                   'system_prompt', a.system_prompt,
                   'model_id', a.model_id,
                   'max_model_calls', a.max_model_calls,
                   'enabled', a.enabled,
                   'tool_ids', COALESCE(
                       (SELECT json_agg(at.tool_id) FROM agent_tools at WHERE at.agent_id = a.id),
                       '[]'::json
                   )
               )
        FROM agents a
    """)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_revisions_agent_id"), table_name="agent_revisions")
    op.drop_table("agent_revisions")
    # ### end Alembic commands ###
