"""v02 tool execution contract

Revision ID: ec3e80993c27
Revises: 3189d7ad9821
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ec3e80993c27"
down_revision: str | Sequence[str] | None = "3189d7ad9821"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tool_executions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("tool_call_id", sa.String(length=100), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("effect_type", sa.String(length=30), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("args_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("result_content", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=40), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "tool_call_id"),
    )
    op.create_index(op.f("ix_tool_executions_run_id"), "tool_executions", ["run_id"], unique=False)
    op.add_column(
        "tools",
        sa.Column("effect_type", sa.String(length=30), server_default="READ_ONLY", nullable=False),
    )
    op.add_column(
        "tools",
        sa.Column(
            "failure_policy", sa.String(length=30), server_default="RETURN_ERROR", nullable=False
        ),
    )
    op.alter_column("tools", "effect_type", server_default=None)
    op.alter_column("tools", "failure_policy", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tools", "failure_policy")
    op.drop_column("tools", "effect_type")
    op.drop_index(op.f("ix_tool_executions_run_id"), table_name="tool_executions")
    op.drop_table("tool_executions")
    # ### end Alembic commands ###
